const nodemailer = require("nodemailer");
const Mailgen = require("mailgen");

// const transporter = nodemailer.createTransport({
//   service: "gmail",
//   port: 465,
//   secure: true,
//   auth: {
//     user: process.env.EMAIL,
//     pass: process.env.EMAIL_PASSKEY,
//   },
// });

// Initialize nodemailer transporter
const transporter = nodemailer.createTransport({
  host: process.env.EMAIL_SERVICE, // host for mailtrap
  port: process.env.EMAIL_PORT,
  // secure: true,
  auth: {
    user: process.env.EMAIL_USERNAME,
    pass: process.env.EMAIL_PASSWORD,
  },
});

// For more info on how mailgen content work visit https://github.com/eladnava/mailgen#readme
// Generate the plaintext version of the e-mail (for clients that do not support HTML)

// Initialize Mailgen instance for generating email templates
const mailGenerator = new Mailgen({
  theme: "default",
  product: {
    name: "e-commerce-api",
    link: "https://github.com/muhammadranju/e-commerce-api",
  },
});

/**
 * Send email using nodemailer transporter
 * @param {Object} options - Options for sending email
 * @param {string} options.email - Recipient email address
 * @param {string} options.subject - Email subject
 * @param {Mailgen.Content} options.mailgenContent - Email content generated by Mailgen
 */
async function sendEmail(options) {
  const emailHtml = mailGenerator.generate(options.mailgenContent);
  const emailTextual = mailGenerator.generatePlaintext(options.mailgenContent);

  // Send email with defined transport object
  const info = await transporter.sendMail({
    // from: `"Google 👻"${process.env.EMAIL}`, // sender address
    from: `"Google"<mail.noreply@gmail.com>`, // sender address
    to: options.email, // Recipient(s) address
    subject: options.subject, /// Email subject
    text: emailTextual, // Plain text body
    html: emailHtml, // HTML body
  });

  console.log("Message successfully sent at: %s", info.messageId);
}

/**
 * Generate Mailgen content for email verification
 * @param {string} username - Username of the recipient
 * @param {string} verificationUrl - Verification URL for email verification
 * @returns {Mailgen.Content} - Mailgen content for email verification
 */
const emailVerificationMailgenContent = (username, verificationUrl) => {
  return {
    body: {
      name: username,
      intro: "Welcome to our app! We're very excited to have you on board.",
      action: {
        instructions:
          "To verify your email please click on the following button:",
        button: {
          color: "#22c55e", // Action button color
          text: "Conform your account →",
          link: verificationUrl, // Verification URL
        },
      },
      outro:
        "Need help, or have questions? Just reply to this email, we'd love to help.",
    },
  };
};

/**
 * Generate Mailgen content for forgot password email
 * @param {string} username - Username of the recipient
 * @param {string} passwordResetUrl - Password reset URL for forgot password process
 * @returns {Mailgen.Content} - Mailgen content for forgot password email
 */
const forgotPasswordMailgenContent = (username, passwordResetUrl) => {
  return {
    body: {
      name: username,
      intro: "We got a request to reset the password of our account",
      action: {
        instructions:
          "To reset your password click on the following button or link:",
        button: {
          color: "#e11d48", // Action button color
          text: "Reset your password →",
          link: passwordResetUrl, // Password reset URL
        },
      },
      outro:
        "Need help, or have questions? Just reply to this email, we'd love to help.",
    },
  };
};

module.exports = {
  sendEmail,
  emailVerificationMailgenContent,
  forgotPasswordMailgenContent,
};
