/* eslint-disable no-undef */
const _config = {
  BASE_URL: process.env.BASE_URL,
  PORT: process.env.PORT,
  MONGODB_URI: process.env.MONGODB_URI,
  MONGODB_URI_LOCAL: process.env.MONGODB_URI_LOCAL,

  ACCESS_TOKEN_SECRET: process.env.ACCESS_TOKEN_SECRET,
  ACCESS_TOKEN_EXPIRY: process.env.ACCESS_TOKEN_EXPIRY,
  REFRESH_TOKEN_SECRET: process.env.REFRESH_TOKEN_SECRET,
  REFRESH_TOKEN_EXPIRY: process.env.REFRESH_TOKEN_EXPIRY,

  SELLER_ACCESS_TOKEN_SECRET: process.env.SELLER_ACCESS_TOKEN_SECRET,
  SELLER_ACCESS_TOKEN_EXPIRY: process.env.SELLER_ACCESS_TOKEN_EXPIRY,
  SELLER_REFRESH_TOKEN_SECRET: process.env.SELLER_REFRESH_TOKEN_SECRET,
  SELLER_REFRESH_TOKEN_EXPIRY: process.env.SELLER_REFRESH_TOKEN_EXPIRY,

  SELLER_COOKIE_SECRET_KEY: process.env.SELLER_COOKIE_SECRET_KEY,
  COOKIE_SECRET_KEY: process.env.COOKIE_SECRET_KEY,

  EMAIL: process.env.EMAIL,
  EMAIL_PASSKEY: process.env.EMAIL_PASSKEY,

  EMAIL_SERVICE: process.env.EMAIL_SERVICE,
  EMAIL_PORT: process.env.EMAIL_PORT,
  EMAIL_USERNAME: process.env.EMAIL_USERNAME,
  EMAIL_PASSWORD: process.env.EMAIL_PASSWORD,

  CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET,

  SSL_STORE_ID: process.env.SSL_STORE_ID,
  SSL_STORE_PASSWORD: process.env.SSL_STORE_PASSWORD,
  SSL_STORE_IS_LIVE: process.env.SSL_STORE_IS_LIVE,

  ENV: process.env.NODE_ENV,
};
const config = Object.freeze(_config);

module.exports = config;
